# Country color assignments (ISO_A3=family.shade)
# Families: Blue=0, Red=1, Green=2, Yellow=3, Orange=4, Purple=5
# Shades: 0=light, 1=medium, 2=dark
ABW=3.1
AFG=4.0
AGO=1.0
AIA=0.0
ALB=1.0
AND=5.0
ARE=3.0
ARG=0.0
ARM=1.0
ASM=1.0
ATA=5.0
ATG=1.0
AUS=0.0
AUT=1.0
AZE=0.1
BDI=2.1
BEL=3.0
BEN=1.1
BES=1.0
BFA=1.0
BGD=2.0
BGR=2.0
BHR=1.0
BHS=5.0
BIH=0.0
BLM=2.0
BLR=2.0
BLZ=5.0
BMU=0.0
BOL=3.0
BRA=2.0
BRB=2.0
BRN=4.0
BTN=0.0
BWA=0.0
CAF=3.0
CAN=1.0
CHE=1.1
CHL=1.0
CHN=3.0
CIV=4.0
CMR=2.0
COD=0.0
COG=2.1
COK=4.0
COL=3.1
COM=5.0
CPV=4.0
CRI=0.0
CUB=0.1
CUW=2.1
CYM=4.0
CYP=4.0
CZE=0.1
DEU=3.1
DJI=5.0
DMA=3.0
DNK=4.0
DOM=2.0
DZA=1.0
ECU=3.0
EGY=1.0
ERI=0.0
ESP=3.0
EST=2.0
ETH=2.0
FIN=0.0
FJI=2.0
FLK=3.0
FRA=0.0
FRO=2.0
FSM=4.0
GAB=0.0
GBR=0.1
GEO=4.0
GGY=4.0
GHA=1.1
GIB=4.0
GIN=1.0
GLP=1.1
GMB=5.0
GNB=4.0
GNQ=5.0
GRC=0.0
GRD=3.1
GRL=3.0
GTM=0.0
GUF=5.0
GUM=2.0
GUY=1.0
HND=1.0
HRV=1.0
HTI=2.1
HUN=2.0
IDN=1.0
IMN=0.0
IRL=2.0
IRN=2.0
IRQ=1.0
ISL=0.0
ISR=0.0
ITA=2.0
JAM=5.0
JOR=2.0
JPN=1.1
KAZ=0.0
KEN=1.0
KGZ=1.0
KHM=0.0
KIR=4.1
KNA=0.0
KOR=0.0
KWT=5.0
LAO=2.0
LBN=1.0
LBR=4.1
LBY=2.1
LCA=2.1
LIE=3.0
LKA=4.0
LSO=0.0
LTU=3.0
LUX=1.0
LVA=1.1
MAR=1.1
MCO=1.0
MDA=0.0
MDG=1.1
MDV=0.0
MEX=2.0
MHL=5.0
MKD=1.1
MLI=2.0
MLT=0.0
MMR=3.1
MNE=3.0
MNG=5.0
MNP=0.1
MOZ=4.0
MRT=5.0
MSR=5.0
MTQ=0.0
MUS=1.1
MWI=1.0
MYS=0.0
MYT=5.1
NAM=0.1
NCL=3.0
NER=4.0
NGA=2.1
NIC=1.1
NIU=5.0
NLD=4.0
NOR=1.1
NPL=2.0
NRU=2.0
NZL=0.1
OMN=4.0
PAK=2.1
PAN=0.1
PCN=3.0
PER=1.1
PHL=0.1
PLW=4.1
PNG=4.1
POL=1.1
PRK=1.1
PRT=1.0
PRY=1.0
PSE=4.0
PYF=3.1
QAT=0.0
REU=1.0
ROU=3.0
RUS=1.0
RWA=1.0
SAU=2.1
SDN=1.1
SEN=2.1
SGP=3.0
SHN=4.0
SLB=2.1
SLE=5.0
SLV=0.1
SMR=0.0
SOM=0.0
SRB=0.1
SSD=0.1
STP=4.0
SUR=0.0
SVK=0.0
SVN=0.0
SWE=0.1
SWZ=5.0
SYC=4.0
SYR=2.1
TCA=0.0
TCD=0.0
TGO=4.0
THA=0.1
TJK=1.1
TKM=2.1
TLS=1.1
TON=1.1
TTO=4.0
TUN=1.1
TUR=1.1
TUV=3.0
TWN=3.1
TZA=2.0
UGA=2.1
UKR=0.1
URY=0.1
USA=0.0
UZB=0.1
VAT=2.0
VCT=4.1
VEN=3.0
VGB=4.0
VIR=4.1
VNM=1.1
VUT=4.0
WLF=0.0
WSM=3.0
XKX=3.1
YEM=2.0
ZAF=2.1
ZMB=2.1
ZWE=2.0
TKL=3.1
IND=4.1
